### ISSUE TITLE
Certificate validation failed 

### ISSUE THREAD

**Issue by ryym** [Jxck/jxck.io#10]
Hi,

I visited your blog site <https://blog.jxck.io> today (2018-09-04) and encountered a certificate validation error. It seems that your certificate is expired?

<img width="858" alt="_" src="https://user-images.githubusercontent.com/12684251/45010916-cee54300-b04a-11e8-9e1e-7e10b3b1a656.png">

I don't know what is a best way to contact you about this so filed this issue.

Thanks.

**Comment by ryym** [comment]
It was fixed!

**Comment by Jxck** [comment]
my cron has failed but fixed.
thanks for reporting :)
