### ISSUE TITLE
[mozaic.fm] Specify play position on URL

### ISSUE THREAD

**Issue by nwtgck** [Jxck/jxck.io#22]
Hi, thank you very much for your wonderful podcast! This issue is a feature request.

I'd like to request a new feature to specify the play position on the URL.
For example,
- https://mozaic.fm/episodes/67/monthly-web-202004.html#t=1205
- https://mozaic.fm/episodes/67/monthly-web-202004.html#1205
- https://mozaic.fm/episodes/67/monthly-web-202004.html?t=1205

This is the same as YouTube does: `https://youtu.be/_LzSBr99kkw?t=2354`

This feature will help us to share mozaic.fm and cite proper position.

**Comment by Jxck** [comment]
currently I don't have plant to do this.
thanks

**Comment by nwtgck** [comment]
Thanks!
