### ISSUE TITLE
font-size: 100em in blog.jxck.io

### ISSUE THREAD

**Issue by hogashi** [Jxck/jxck.io#24]
Hi, I've found an element applied a style `font-size: 100em` in your blog and I also found your guide on your code: https://github.com/Jxck/jxck.io/blob/2bbd16ba35d353519a8921f06f9f68cd935cfc83/www.jxck.io/assets/css/pre.css#L204

`100em` is at https://blog.jxck.io/entries/2019-08-14/nullish-coalescing-optional-chaining.html#optional-chaining .  I hope it will be fixed and be better!

**Comment by Jxck** [comment]
thanks!
