### ISSUE TITLE
link to another draft

### ISSUE THREAD

**Issue by thekuwayama** [Jxck/jxck.io#54]
Hi, thank you very much for your interesting [blog post](https://blog.jxck.io/entries/2022-02-05/http3.html)!

I think that draft about HTTPS RR is the following:

```diff
- https://datatracker.ietf.org/doc/html/draft-bellis-dnsop-http-record-00
+ https://datatracker.ietf.org/doc/html/draft-ietf-dnsop-svcb-https-08
```

**Comment by Jxck** [comment]
Good catch, Thanks !

**Comment by thekuwayama** [comment]
Thanks !
