### ISSUE TITLE
history-of-url-bar: Chromeのリリース時期が違う

### ISSUE THREAD

**Issue by myakura** [Jxck/jxck.io#75]
> 推定すると、 Chrome は 2010 年にリリースされ、初期のころからこの UI だったように思う。

https://github.com/Jxck/jxck.io/blob/main/blog.jxck.io/entries/2023-05-28/history-of-url-bar.md?plain=1#L37

Chromeがリリースされたのは2008年です。
https://googleblog.blogspot.com/2008/09/fresh-take-on-browser.html

当初はベータですが、それも2008年末に取れてます。
https://googleblog.blogspot.com/2008/12/google-chrome-beta.html

**Comment by Jxck** [comment]
thanks
