### ISSUE TITLE
example.com のサブドメイン間は Cross Site ではなく Same Site ではないでしょうか

### ISSUE THREAD

**Issue by sztm** [Jxck/jxck.io#86]
https://github.com/Jxck/jxck.io/blob/a270feff990cac8fcb50508ee464e8fe05a2c991/blog.jxck.io/entries/2023-12-28/related-website-sets.md?plain=1#L22-L34

example.com が registrable domains とするなら

- cdn.example.com
- id.example.com
- mail.example.com

は Same Site となるかと思いました。
仮に example.com を PSL とするなら Cross Site になる理解ですが、「用途毎にサブドメインを切る運用」と書いてあるので PSL 想定ではないように感じました。

自分の認識が誤っていたらすみません。

参考: https://developer.mozilla.org/en-US/docs/Glossary/Site#examples
> These are the same site because the registrable domain of mozilla.org is the same:
> 
> https://developer.mozilla.org/en-US/docs/
> https://support.mozilla.org/en-US/

(アドカレ読んでいます。いつもWebの仕組みについて経緯を含めてわかりやすく整理されていて勉強になります。ありがとうございます。)

**Comment by Jxck** [comment]
Good Catch.
Thanks 👍
