### ISSUE TITLE
mozaic.fm ep140の回の日付がおかしい

### ISSUE THREAD

**Issue by myakura** [Jxck/jxck.io#92]
https://github.com/Jxck/jxck.io/blob/4b7d4983cbe59f0cdf46675f5e9387459381d579/mozaic.fm/episodes/140/monthly-platform-202401.md?plain=1#L5

日付であるはずのところにエピソード番号が入っています。

https://github.com/Jxck/jxck.io/blob/4b7d4983cbe59f0cdf46675f5e9387459381d579/feed.mozaic.fm/index.json#L44

なのですごい過去の日付で公開されている感じ。

**Comment by Jxck** [comment]
already fixed, thanks
